server:
  port: 8082
spring:
  application:
    name: Leave-Service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/leaves
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    instance:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

