server:
  port: 8081
spring:
  application:
    name: Employee-Service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/